export default {
    SET_WAREHOUSE: 'SET_WAREHOUSE',
    SET_PRIORITY_WAREHOUSE: 'SET_PRIORITY_WAREHOUSE',
    SET_PRIORITY_TRUCK: 'SET_PRIORITY_TRUCK',
    SET_SELECTED_ORDER: 'SET_SELECTED_ORDER',
    SET_STEP: 'SET_STEP',
    //schedule
    SET_TRUCKS: 'SET_TRUCKS',
    SET_FIND_TRUCKS: 'SET_FIND_TRUCKS',
    SET_DIRECTION_NAME: 'SET_DIRECTION_NAME',
    SET_NEW_EVENT: 'SET_NEW_EVENT',
}