export default {
    SET_WAREHOUSE: 'SET_WAREHOUSE',
    SET_PRIORITY_WAREHOUSE: 'SET_PRIORITY_WAREHOUSE',
    SET_PRIORITY_TRUCK: 'SET_PRIORITY_TRUCK',
    SET_SELECTED_ORDER: 'SET_SELECTED_ORDER',
}