export default {
    SET_WAREHOUSE: 'SET_WAREHOUSE',
    SET_PRIORITY_WAREHOUSE: 'SET_PRIORITY_WAREHOUSE',
    SET_PRIORITY_TRUCK: 'SET_PRIORITY_TRUCK',
    SET_SELECTED_ORDER: 'SET_SELECTED_ORDER',
    SET_STEP: 'SET_STEP',
    //hint
    SET_ORDERS: 'SET_ORDERS',
    ADD_ORDERS: 'ADD_ORDERS',
    SET_ADDRESS: 'SET_ADDRESS',
    SET_DIRECTION_TEMPLATES: 'SET_DIRECTION_TEMPLATES',
    SET_DIRECTION_REQUEST: 'SET_DIRECTION_REQUEST',
    SET_CURRENT_DIRECTION: 'SET_CURRENT_DIRECTION',
    SET_WAYPOINTS: 'SET_WAYPOINTS',
    SET_ORDER_ADDRESS: 'SET_ORDER_ADDRESS',
    //schedule
    SET_TRUCKS: 'SET_TRUCKS',
    SET_FIND_TRUCKS: 'SET_FIND_TRUCKS',
    SET_DIRECTION_NAME: 'SET_DIRECTION_NAME',
    SET_NEW_EVENT: 'SET_NEW_EVENT',
    SET_TRUCK: 'SET_TRUCK',
}