export default {
    SET_LICENSE_PLATES: 'SET_LICENSE_PLATES',
    SET_MAKER: 'SET_MAKER',
    SET_NAME: 'SET_NAME',
    SET_SIZE: 'SET_SIZE',
    SET_STATUS: 'SET_STATUS',
    SET_TYPE: 'SET_TYPE',
    SET_WAREHOUSE: 'SET_WAREHOUSE',
    SET_WEIGHT: 'SET_WEIGHT',
}