export default {
    SET_EVENTS: 'SET_EVENTS',
    SET_FROM_DATE: 'SET_FROM_DATE',
    SET_TO_DATE: 'SET_TO_DATE',
    FETCH_EVENTS: 'FETCH_EVENTS',
    SET_TRUCKS: 'SET_TRUCKS',
    SET_CURRENT_TRUCK: 'SET_CURRENT_TRUCK',
    SET_CURRENT_EVENT: 'SET_CURRENT_EVENT',
}