export default {
    SET_TRUCK_VISIBLE: 'SET_TRUCK_VISIBLE',
    SET_ORDER_VISIBLE: 'SET_ORDER_VISIBLE',
    SET_ORDERS: 'SET_ORDERS',
    ADD_ORDERS: 'ADD_ORDERS',
    ADD_DODGE_ADDRESS: 'ADD_DODGE_ADDRESS',
    SET_ADDRESS: 'SET_ADDRESS',
    SET_DIRECTION_TEMPLATES: 'SET_DIRECTION_TEMPLATES',
    SET_DIRECTION_REQUEST: 'SET_DIRECTION_REQUEST',
    SET_CURRENT_DIRECTION: 'SET_CURRENT_DIRECTION',
    SET_WAYPOINTS: 'SET_WAYPOINTS',
    SET_ORDER_ADDRESS: 'SET_ORDER_ADDRESS'
}