export default {
    SET_TRUCK_VISIBLE: 'SET_TRUCK_VISIBLE',
    SET_ORDER_VISIBLE: 'SET_ORDER_VISIBLE',
    SET_ORDERS: 'SET_ORDERS',
    ADD_DODGE_ADDRESS: 'ADD_DODGE_ADDRESS',
    SET_ADDRESS: 'SET_ADDRESS',
}