export default {
    SET_DATA_SOURCE: 'SET_DATA_SOURCE',
    SET_PAGINATION: 'SET_PAGINATION',
    SET_SELECTED_ROW_KEYS: 'SET_SELECTED_ROW_KEYS',
    SET_KEYWORD: 'SET_KEYWORD',
    SET_FROM_DATE: 'SET_FROM_DATE',
    SET_TO_DATE: 'SET_TO_DATE',
    SET_URGENCY: 'SET_URGENCY',
    SET_IN_DAY: 'SET_IN_DAY',
    SET_NORMAL: 'SET_NORMAL',
    SET_UNSET: 'SET_UNSET',
    SET_READY: 'SET_READY',
    SET_FINISH: 'SET_FINISH',
    SET_PROGRESS: 'SET_PROGRESS'
}