export default {
    SET_DATA_SOURCE: 'SET_DATA_SOURCE',
    SET_PAGINATION: 'SET_PAGINATION',
    SET_SELECTED_ROW_KEYS: 'SET_SELECTED_ROW_KEYS',
    SET_PRIORITY_WAREHOUSE: 'SET_PRIORITY_WAREHOUSE',
    SET_PRIORITY_TRUCK: 'SET_PRIORITY_TRUCK',
}