export default {
    SET_DATA_SOURCE: 'SET_DATA_SOURCE',
    SET_PAGINATION: 'SET_PAGINATION',
    SET_SELECTED_ROW_KEYS: 'SET_SELECTED_ROW_KEYS',
    SET_KEYWORD: 'SET_KEYWORD',
    SET_FROM_DATE: 'SET_FROM_DATE',
    SET_TO_DATE: 'SET_TO_DATE',
    SET_OPENING: 'SET_OPENING',
    SET_PROMOTION: 'SET_PROMOTION',
    SET_URGENCY: 'SET_URGENCY',
    SET_IN_DAY: 'SET_IN_DAY',
    SET_DELIVERY_TYPE: 'SET_DELIVERY_TYPE',
    SET_WAREHOUSE_TYPE: 'SET_WAREHOUSE_TYPE',
}