export default {
    SET_TRUCK_DATA: 'SET_TRUCK_DATA',
    SET_INFO_DATA: 'SET_INFO_DATA',
    SET_FETCH: 'SET_FETCH',
    SET_ORIGIN: 'SET_ORIGIN',
    SET_WAYPOINTS: 'SET_WAYPOINTS',
    SET_ORDER_ADDRESS: 'SET_ORDER_ADDRESS',
    SET_ORDERS: 'SET_ORDERS',
    SET_IS_EDIT: 'SET_IS_EDIT',
    SET_STEP: 'SET_STEP',
    SET_TRUCK: 'SET_TRUCK',
    SET_EVENT: 'SET_EVENT',
    SET_DIRECT: 'SET_DIRECT'
}